a = {
    "e": {
        "e": ["blue", 92, -20, "red", "yellow", 129, 99, "yellow", 38],
        "a": 98,
        "d": 129,
        "c": -5,
        "h": "green",
        "b": "violet",
        "g": "blue",
        "f": "yellow",
        "i": "red",
    },
    "a": "blue",
    "d": [
        [20, 87, "red", 124, -2, "yellow", "red", 17, "violet", "yellow"],
        {"c": "violet", "a": "red", "b": 161},
        104,
        {
            "e": [
                "blue",
                [51, 47, 57, -41, "green", 149, -11, "red", 103, "orange"],
                "violet",
                72,
                "red",
                ["orange", "blue", "red"],
                -8,
                {"c": "violet", "a": 68, "b": -43, "d": "green"},
                "orange",
            ],
            "a": 36,
            "d": [
                "orange",
                "green",
                "green",
                106,
                "green",
                "red",
                "red",
                "red",
                "violet",
            ],
            "j": {"a": "red", "b": 144},
            "c": 166,
            "h": 109,
            "b": [{"a": 56, "b": "red"}, -41, "blue", 36, 20, "blue", "blue"],
            "g": 188,
            "f": "yellow",
            "i": -7,
        },
        [
            155,
            ["green", "green", 0, "red", "blue"],
            {
                "e": 144,
                "c": "green",
                "a": "orange",
                "b": 133,
                "d": 10,
                "f": [91, 160, "blue", 183, 18, 43, 85, -37],
            },
            {
                "e": "violet",
                "a": -35,
                "d": 57,
                "c": "violet",
                "h": 17,
                "b": "orange",
                "g": 57,
                "f": "red",
                "i": "blue",
            },
            "red",
            "red",
            "green",
            "red",
            29,
            {
                "e": 112,
                "c": ["red", "blue", 68, "red", "yellow"],
                "a": "blue",
                "g": "blue",
                "b": {"a": "red"},
                "d": 162,
                "f": "green",
            },
        ],
        "green",
        [42, "orange"],
        [["yellow", 183, 2, "red", 115, "red", -31]],
    ],
    "j": 29,
    "c": {
        "e": [
            {
                "c": "orange",
                "a": {
                    "e": "orange",
                    "c": -47,
                    "a": "blue",
                    "b": 35,
                    "d": 25,
                    "f": "blue",
                },
                "b": 111,
                "d": 16,
            },
            -44,
            -22,
            179,
            "yellow",
            84,
        ],
        "a": {
            "e": 178,
            "a": ["red", 183, 92],
            "d": 163,
            "c": 105,
            "h": 24,
            "b": "violet",
            "g": -26,
            "f": [125, "green", "violet"],
            "i": "red",
        },
        "d": [
            [12, "yellow", "blue", "green"],
            144,
            [114, "orange", 92, "blue", ["violet", 40, "blue"], 67, 105],
            ["orange", 155, "violet", 37, -38],
        ],
        "j": {
            "a": {
                "c": ["green", "yellow", -13, "green", "red"],
                "a": [-27],
                "b": "violet",
            },
            "b": ["red", [109, 57], 181, "blue", 193, -32, 83, "violet"],
        },
        "c": 128,
        "h": 21,
        "b": {
            "e": "red",
            "a": "red",
            "d": "green",
            "c": ["green", {"a": "blue"}],
            "h": "orange",
            "b": {"e": 199, "c": 35, "a": 126, "b": 183, "d": 60},
            "g": "orange",
            "f": "violet",
            "i": 105,
        },
        "g": "yellow",
        "f": 133,
        "i": [
            {"c": "violet", "a": "yellow", "b": "orange", "d": 144},
            "red",
            "yellow",
            "green",
            105,
            72,
            "red",
            "yellow",
        ],
    },
    "h": [
        "violet",
        [
            [161, "red", "blue", [98, "red", "violet"], "orange", 51, "violet"],
            "violet",
            -6,
            "orange",
            "yellow",
            51,
        ],
        {
            "e": 72,
            "a": [190, "red", "blue", -13, 90, "blue", -6, "violet", 137, 61],
            "d": [126, ["red", 101, 118], 13, "blue", -4, "blue", [47, 157, 77]],
            "c": "orange",
            "h": 176,
            "b": {
                "c": [67, "green", 59, "green", 140, "orange", "blue", 15, 53],
                "a": 162,
                "b": "orange",
                "d": 47,
            },
            "g": 49,
            "f": "yellow",
            "i": "violet",
        },
    ],
    "b": {
        "e": 132,
        "c": [
            ["blue", 142, "violet", "green", 75, 56, "green", "green"],
            "red",
            185,
            "orange",
            "violet",
        ],
        "a": 144,
        "b": "violet",
        "d": {
            "e": "green",
            "a": "blue",
            "d": "violet",
            "c": ["violet", "yellow", "orange", "green", 121, "blue", -23],
            "h": "violet",
            "b": "yellow",
            "g": -34,
            "f": 147,
            "i": 127,
        },
        "f": -25,
    },
    "g": "green",
    "f": "blue",
    "i": 80,
}

print(a.values())
